### ISSUE TITLE
Mình không compile đc thư viện này khi dùng esp32 

### ISSUE THREAD

**Issue by trieu94** [khoih-prog/Blynk_Esp8266AT_WM#1]
Bạn có thể hướng dẫn mình để sử dụng cho esp32 sim800l, mình không complie được với thư viện này

**Comment by khoih-prog** [comment]
You're using the wrong library.

To use ESP32 with GSM/GPRS shields, such as SIM800L, SIM900L, etc. you have to use [**BlynkGSM_Manager library**](https://github.com/khoih-prog/BlynkGSM_Manager).

Have a look at this example
1. [**ESP32_GSM**](https://github.com/khoih-prog/BlynkGSM_Manager/tree/master/examples/ESP32_GSM)
2. [**TTGO_TCALL_GSM**](https://github.com/khoih-prog/BlynkGSM_Manager/tree/master/examples/TTGO_TCALL_GSM) for ESP32-based TTGO-TCALL
